### ISSUE TITLE
Passwordless auth works, but token collection is empty

### ISSUE THREAD

**Issue by simevidas** [florianheinemann/passwordless-mongostore#11]
I’ve recently implemented Passwordless on my site. The system works: I can use `req.user` to retrieve the verified email of the visitor. However, I’ve connected to my MongoDB database and noticed the the token collection has a size of `0`, despite dozens of successful logins. 

My code:

```js
var PassStore = require('passwordless-mongostore');
var url = require('./mongodb-url'); // this URL is used across my app and works

passwordless.init(new PassStore(url, { mongostore: { collection: 'tokens' }}));
```

The ‘tokens’ collection seems to be empty:

![capture](https://cloud.githubusercontent.com/assets/716405/20950293/3520a474-bc1f-11e6-91b6-5b1bfd68b699.PNG)

Is the size supposed to be zero? Maybe because it’s encrypted, so it’s invisible?

**Comment by florianheinemann** [comment]
I think it's great that you started digging into it and try to understand what's happening under the hood! The behavior is indeed the expected one - even though it might be counterintuitive. The tokens are deleted after they've been used. As the tokens are equivalent to passwords we don't want them to stay around forever risking e.g., a breach of the email account of the user. 

In some cases people want the tokens to be valid for several logins or a longer time. That can be set here:
- https://passwordless.net/deepdive#allow-token-reuse
- https://passwordless.net/deepdive#modify-lifetime-of-a-token

If you want to check the current behavior just use your interface to generate a new token. If you then query your database you should see one new entry. After then clicking on the token and logging in the token should disappear from the database!

Hope that helps!

**Comment by simevidas** [comment]
Aaah, I see. They’re only stored temporarily, because they’re no longer valid (by default) after the user has used them. Makes sense!
